# -*- coding: utf-8 -*-
"""facebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ojLTIiKJqGMR_9ytMnJ6mqH1gKeNWti0
"""

import pandas as pd

comsur = pd.read_csv('MSDS-Orientation-Computer-Survey(in).csv')

print(comsur.head())

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.hist(comsur['Hard Drive Size (in GB)'], bins=70, edgecolor='k', alpha=0.7)
plt.title(f'Histogram of Hard Drive Size')
plt.xlabel(column_name)
plt.ylabel('Frequency')
plt.grid(True)
plt.show()